### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by vinaykothinti** [forwardadvance/ng-tweets#2]
Hi

Tweets are not showing in firefox showing wrong json format please the screenshots of chrome and firefox.

![image](https://cloud.githubusercontent.com/assets/3306322/8109333/aadb611c-1073-11e5-9519-3215e475f307.png)

![image](https://cloud.githubusercontent.com/assets/3306322/8109386/fb7711ac-1073-11e5-837c-43c113f7ca9e.png)

![image](https://cloud.githubusercontent.com/assets/3306322/8109350/c1c021ba-1073-11e5-97ec-1f0679d50335.png)

![image](https://cloud.githubusercontent.com/assets/3306322/8109392/083783e0-1074-11e5-92a7-91b3a2ddd36d.png)

 Thanks

**Comment by nicholas-johnson** [comment]
Thanks for the feedback, I will need to fix this.

**Comment by nicholas-johnson** [comment]
Issue was with innerText vs. textContent. This is now fixed.
