### ISSUE TITLE
Widget has changed formatting

### ISSUE THREAD

**Issue by ersgonzalo** [forwardadvance/ng-tweets#5]
It seems like Twitter has changed the way that their tweets are outputted via the JSONP callback. As a result, the demo doesn't seem to work anymore. 

I'm looking into it from my own side but I'm letting you know too just in case. If i find a solution, I'll send a pull request!

**Comment by nicholas-johnson** [comment]
It has indeed. Am working on a fix that will be a bit more maintainable.

**Comment by nicholas-johnson** [comment]
Thanks for the PR. Now marking this as closed.
